name: Amazing Group
favicon: null
layout_spectrum: 0.36325591313652694
typography_spectrum: 0.7842763424851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08965952368453145
  lightness: 0.3088165398221463
  saturation: 0.8621336258947849
  rhythmicContrast: 0.6337618420366198
purpose: []
