name: Amazing Group
favicon: null
layout_spectrum: 0.53638
typography_spectrum: 0.34215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#fef035'
    - '#1eb4ed'
    - '#73bd4c'
    - '#e9168c'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
